# Generated by Django 3.0.5 on 2020-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20200413_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='depts',
            field=models.ManyToManyField(to='rbac.Organization', verbose_name='权限范围'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
