# Generated by Django 3.0.5 on 2020-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20200414_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('公司', '公司'), ('部门', '部门')], default='部门', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='role',
            name='depts',
            field=models.ManyToManyField(blank=True, to='rbac.Organization', verbose_name='权限范围'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ManyToManyField(blank=True, to='rbac.Position', verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='角色'),
        ),
    ]
